# GitHub Pages Configuration

theme: jekyll-theme-minimal
baseurl: "/wellsofchange"
url: "https://jonyfs.github.io"
title: "Wells of Change - NGO Website"
description: "Making clean water accessible to everyone, everywhere."

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - wellsofchange.code-workspace
  - "*.puml"